### ISSUE TITLE
Use Binomial species epithet name in germplasm species field

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/BrAPI#428]
https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmSearchRequest.yaml#L40

https://en.wikipedia.org/wiki/Binomial_nomenclature
I have requested the separation of genus & species field. But on a second thougth, for searching without ambiguity ( eg populus nigra and pinus nigra ), it is better to search on the full string. We are concatenating in our system in a genus_species_subtaxa field. A discussion to dig up ?
Or it could also be searching by a tax_id, but not all taxon have a reference.

**Comment by BrapiCoordinatorSelby** [comment]
Good discussion topic, not critical for V2.0.
Can wait for a future release for a final decision.

**Comment by jeback1** [comment]
It is an interesting idea but I agree that we could set it aside for v2.

**Comment by BrapiCoordinatorSelby** [comment]
Here is an example of why this issue is important and needs to be fixed. I would like to search for two different species in different genus's. In this example I will search for "Pinus resinosa" (red pine) and "Ilex glabra" (Appalachian tea). 
In V2.0, the only way to do this is to construct a search request like the one below:
```
{
  "genus" : ["Pinus", "Ilex"],
  "species" : ["resinosa", "glabra"]
}
```
This would return the expected results for "Pinus resinosa" and "Ilex glabra", but because of the nature of the search query, it would also pick up results for "Pinus glabra" and "Ilex resinosa". "Pinus glabra" (spruce pine) does exist and could return as an unexpected false positive to this search.
This is obviously a contrived example, and the chances of this scenario happening in the real world are rare, but not impossible. 

By adding a new search parameter `binomialNames` this issue can be avoided with a more precise search.
