### ISSUE TITLE
Observation variable scale object min/max valid field type for dates

### ISSUE THREAD

**Issue by nickpalladino** [plantbreeding/BrAPI#450]
The min/max fields are specified as integer types but are meant to be able to represent dates as well as numeric types. Talked with Pete about being changed to string type to support this.

**Comment by BrapiCoordinatorSelby** [comment]
@nickpalladino
Unfortunately, I can't just make a type change from `int` to `string` because it would break backward compatibility. Granted, it is a very small break, but can still cause problems and confusion.

My plan is to deprecate the existing fields `min` and `max`, then create new string fields `minimumValue` and `maximumValue`. This way, a single server is able to support V2.0 and V2.1 clients simultaneously.

Let me know if you have any concerns.
